import React from "react";

const Blog3 = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6 text-gray-800">
      {/* Sections */}
      <section className="mb-8">
       <h2 className="text-2xl font-bold mb-4 mt-6 text-imp-text">What Is Net Metering?</h2>
        <p>Net metering is a billing mechanism that allows you to:</p>
        <ul className="list-disc ml-6">
          <li>Export extra electricity generated by your solar system to the grid</li>
          <li>Receive credit for that exported electricity on your bill</li>
        </ul>
        <p>In short: you’re paid for the solar power you don’t use.</p>
      </section>

      <section className="mb-8">
       <h2 className="text-2xl font-bold mb-4 mt-6 text-imp-text">How Net Metering Works (Step by Step)</h2>
        <ol className="list-decimal ml-6">
          <li>Your solar panels generate electricity during the day.</li>
          <li>You use that electricity to power your home or business.</li>
          <li>If your system generates more than you need, excess is exported to the grid.</li>
          <li>A net meter tracks both:
            <ul className="list-disc ml-6 mt-2">
              <li>Units imported from the grid</li>
              <li>Units exported to the grid</li>
            </ul>
          </li>
          <li>At billing time: <strong>Net Units = Imported – Exported</strong></li>
        </ol>

        <h3 className="mt-4">Example: Net Metering in Action</h3>
        <ul className="list-disc ml-6">
          <li>Your system generates 400 units</li>
          <li>You consume 300 units</li>
          <li>You export 100 units</li>
          <li>You import 50 units (at night)</li>
        </ul>
        <p>Net units billed = 50 – 100 = –50 units → a credit of 50 units, adjusted in your next bill.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4 mt-6 text-imp-text">How Net Metering Saves You Money in 2025</h2>
        <ul className="list-disc ml-6">
          <li>Lower monthly bills (up to 80–90% savings)</li>
          <li>Export offsets imports</li>
          <li>Possibility of zero-bill if generation ≥ consumption</li>
          <li>No wastage of unused solar power</li>
          <li>Higher ROI on your solar investment</li>
        </ul>
      </section>

      <section className="mb-8">
       <h2 className="text-2xl font-bold mb-4 mt-6 text-imp-text">Net Metering Policy in Delhi and Uttar Pradesh (2025)</h2>

        <h3 className="mt-4">Delhi (BRPL/BYPL/TPDDL/NDMC)</h3>
        <ul className="list-disc ml-6">
          <li>Applies to all consumers (domestic, commercial, industrial)</li>
          <li>No solar capacity limit</li>
          <li>Central subsidy under PM Surya Ghar Yojana</li>
          <li>State subsidy under Delhi Solar Energy Policy 2023</li>
          <li>Bills often drop to ₹0 or even negative</li>
        </ul>

        <h3 className="mt-4">Uttar Pradesh (UPNEDA/Discoms)</h3>
        <ul className="list-disc ml-6">
          <li>Available for residential, agricultural, govt & private institutions</li>
          <li>Capacity: 1 KW – 2 MW, limited to sanctioned load</li>
          <li>Application filed with UPNEDA or local DISCOM</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2>Important Notes for 2025</h2>
        <ul className="list-disc ml-6">
          <li>Net billing is being introduced for large commercial projects in parts of India.</li>
          <li>Net metering is still available for residential and small commercial systems in Delhi/UP.</li>
          <li>Always check latest DISCOM rules or consult your solar installer.</li>
        </ul>

        <p className="mt-2 font-semibold">🤝 How Solar Radian Helps You</p>
        <ul className="list-disc ml-6">
          <li>Application submission to DISCOM</li>
          <li>Technical approvals and paperwork</li>
          <li>Bidirectional/net meter installation</li>
          <li>Follow-up until activation</li>
        </ul>
        <p>Our team ensures a smooth process — whether in Delhi NCR, Lucknow, Kanpur, Meerut, or nearby cities.</p>
      </section>

      <section className="mb-8">
       <h2 className="text-2xl font-bold mb-4 mt-6 text-imp-text">Final Thoughts</h2>
        <p>Net metering makes solar financially smart. It turns your roof into a mini power plant and rewards you for clean energy contribution.</p>
        <p>If you’re installing solar in 2025, ensure your system is net-metering enabled — and let the savings begin.</p>

      </section>
    </div>
  );
};

export default Blog3;
