import React from "react";
import {
  FaSolarPanel,
  FaRupeeSign,
  FaFileInvoice,
  FaBolt,
  FaHandshake,
  FaCheckCircle,
} from "react-icons/fa";

const NetMetering = () => {
  return (
    <div className="bg-gray-50 min-h-screen text-gray-800 ">
      {/* Header Section */}
      <header className="bg-gradient-to-r from-imp-text to-orange-300 py-10 text-center text-white shadow-md">
        <h1 className="text-3xl md:text-4xl font-bold">
          What Is Net Metering?
        </h1>
        <p className="mt-3 text-base max-w-3xl mx-auto">
          Understand how net metering turns your solar system into a source of
          income — and why it’s key to maximizing your savings in 2025.
        </p>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto p-6 md:p-10 space-y-10">
        {/* Intro */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600 flex items-center gap-2">
            <FaFileInvoice /> What Is Net Metering?
          </h2>
          <p className="mt-3 leading-relaxed text-base">
            Net metering is a billing mechanism that allows you to:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-base">
            <li>Export extra electricity generated by your solar system to the grid.</li>
            <li>Receive credit for that exported electricity on your bill.</li>
          </ul>
          <p className="mt-3 font-semibold text-base">
            In short: you’re paid for the solar power you don’t use.
          </p>
        </section>

        {/* Step-by-Step Section */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600 flex items-center gap-2">
            <FaBolt /> How Net Metering Works (Step by Step)
          </h2>
          <ol className="list-decimal list-inside mt-4 space-y-2 text-base">
            <li>Your solar panels generate electricity during the day.</li>
            <li>You use that electricity to power your home or business.</li>
            <li>If your system generates more than you need, excess is exported to the grid.</li>
            <li>A net meter tracks both:
              <ul className="list-disc list-inside ml-6 mt-1 text-base">
                <li>Units imported from the grid</li>
                <li>Units exported to the grid</li>
              </ul>
            </li>
            <li>At billing time: <span className="font-semibold">Net Units = Imported – Exported</span></li>
          </ol>
        </section>

        {/* Example Section */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600">
            Example: Net Metering in Action
          </h2>
          <div className="mt-4 space-y-2 text-base">
            <p>🔹 Your system generates: <span className="font-semibold">400 units</span></p>
            <p>🔹 You consume: <span className="font-semibold">300 units</span></p>
            <p>🔹 You export: <span className="font-semibold">100 units</span></p>
            <p>🔹 You import: <span className="font-semibold">50 units (at night)</span></p>
            <p className="mt-4 font-semibold text-green-700">
              Net units billed = 50 – 100 = –50 units → a credit of 50 units,
              adjusted in your next bill.
            </p>
          </div>
        </section>

        {/* Savings Section */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600 flex items-center gap-2">
            <FaRupeeSign /> How Net Metering Saves You Money in 2025
          </h2>
          <ul className="list-disc list-inside mt-3 space-y-2 text-base">
            <li>Lower monthly bills (up to 80–90% savings)</li>
            <li>Export offsets imports</li>
            <li>Possibility of zero-bill if generation ≥ consumption</li>
            <li>No wastage of unused solar power</li>
            <li>Higher ROI on your solar investment</li>
          </ul>
        </section>

        {/* Delhi & UP Policy Section */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600">
            Net Metering Policy in Delhi and Uttar Pradesh (2025)
          </h2>

          <div className="grid md:grid-cols-2 gap-6 mt-6">
            {/* Delhi */}
            <div className="border border-gray-200 rounded-xl p-5 text-base">
              <h3 className="text-xl font-semibold text-green-700 mb-2">
                Delhi (BRPL / BYPL / TPDDL / NDMC)
              </h3>
              <ul className="list-disc list-inside space-y-1">
                <li>Applies to all consumers (domestic, commercial, industrial)</li>
                <li>No solar capacity limit</li>
                <li>Central subsidy under PM Surya Ghar Yojana</li>
                <li>State subsidy under Delhi Solar Energy Policy 2023</li>
                <li>Bills often drop to ₹0 or even negative</li>
              </ul>
            </div>

            {/* Uttar Pradesh */}
            <div className="border border-gray-200 rounded-xl p-5 text-base">
              <h3 className="text-xl font-semibold text-blue-700 mb-2">
                Uttar Pradesh (UPNEDA / Discoms)
              </h3>
              <ul className="list-disc list-inside space-y-1">
                <li>Available for residential, agricultural, govt & private institutions</li>
                <li>Capacity: 1 KW – 2 MW, limited to sanctioned load</li>
                <li>Application filed with UPNEDA or local DISCOM</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Important Notes */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600 mb-3">
            Important Notes for 2025
          </h2>
          <ul className="list-disc list-inside space-y-1 text-base">
            <li>Net billing is being introduced for large commercial projects in parts of India.</li>
            <li>Net metering is still available for residential and small commercial systems in Delhi/UP.</li>
            <li>Always check latest DISCOM rules or consult your solar installer.</li>
          </ul>
        </section>

        {/* How Solar Radian Helps */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-2xl font-bold text-orange-600 flex items-center gap-2">
            <FaHandshake /> How Solar Radian Helps You
          </h2>
          <ul className="list-disc list-inside mt-3 space-y-2 text-base">
            <li>Application submission to DISCOM</li>
            <li>Technical approvals and paperwork</li>
            <li>Bidirectional/net meter installation</li>
            <li>Follow-up until activation</li>
          </ul>
          <p className="mt-3 font-medium text-gray-700 text-base">
            Our team ensures a smooth process — whether in Delhi NCR, Lucknow,
            Kanpur, Meerut, or nearby cities.
          </p>
        </section>

        {/* Final Thoughts */}
        <section className="bg-white rounded-2xl shadow-md p-6">
          <h2 className="text-3xl font-bold">Final Thoughts</h2>
          <p className="mt-4 max-w-3xl mx-auto text-base">
            Net metering makes solar financially smart. It turns your roof into a
            mini power plant and rewards you for clean energy contribution.
          </p>
          <p className="mt-4 font-semibold text-base">
            If you’re installing solar in 2025, ensure your system is net-metering
            enabled — and let the savings begin!
          </p>
        </section>
      </main>
    </div>
  );
};

export default NetMetering;
