import React, { useState } from 'react';
import { motion } from 'framer-motion';

const Faq = () => {
  const [openItems, setOpenItems] = useState({});
  const [searchTerm, setSearchTerm] = useState('');

  const toggleItem = (index) => {
    setOpenItems(prevState => ({
      ...prevState,
      [index]: !prevState[index]
    }));
  };

  const faqData = [
    {
      question: "What is a Grid Connected Rooftop Solar PV System?",
      answer: `<p>In grid-connected rooftop or small solar photovoltaic (SPV) systems, the direct current (DC) electricity generated by the SPV panels is converted into alternating current (AC) using a Power Conditioning Unit (PCU). This AC power is then supplied to the grid.</p>
      <p>During daylight hours, these SPV systems generate electricity, which is primarily used to power local loads. Any surplus electricity is fed back into the grid, provided it is operational. When solar power generation is insufficient—such as during cloudy weather—the required electricity for local loads is drawn from the grid.</p>`
    },
    {
      question: "What are the Main Components of a Grid-Connected Rooftop Solar PV System?",
      answer: `<p><strong>1. Solar PV Modules/Panels:</strong></p>
      <p>These modules convert sunlight into direct current (DC) electricity. They come in various technologies such as crystalline silicon, thin-film silicon, CIGS, CdTe, and HIT, with crystalline silicon being the most commonly used in rooftop systems. Multiple panels are connected to form arrays, tailored to the system's desired capacity.</p>
      
      <p><strong>2. Inverter:</strong></p>
      <p>The inverter plays a critical role by converting the variable DC output from the solar panels into alternating current (AC) power, which can be used by appliances or fed into the grid. It also ensures synchronization with the grid to facilitate seamless power injection.</p>
      
      <p><strong>3. Module Mounting Structure:</strong></p>
      <p>This structure provides sturdy support to the solar panels throughout their lifespan and withstands various weather conditions. For rooftop systems, these structures are usually fixed at specific angles and orientations but can also be equipped with trackers that follow the Sun to maximize energy capture.</p>
      
      <p><strong>4. Bi-directional Meters:</strong></p>
      <p>These meters, also known as net meters, monitor the energy flow. They track the amount of electricity generated and fed into the grid by the solar PV system and the electricity drawn from the grid when needed.</p>
      
      <p><strong>5. Balance of System (BoS):</strong></p>
      <p>This includes all additional components required for the system's functioning, such as cables, switchboards, junction boxes, earthing systems, circuit breakers, fuses, and lightning protection systems. These elements ensure safety, efficiency, and reliability of the overall system.</p>`
    },
    {
      question: "Where Can Such Solar PV Systems Be Installed?",
      answer: `<p>Solar photovoltaic (SPV) systems can be installed in a variety of locations, including:</p>
      <ul>
        <li>Rooftops of residential buildings and housing societies.</li>
        <li>Commercial complexes such as malls, offices, and business parks.</li>
        <li>Community centers and public spaces.</li>
        <li>Government organizations and offices.</li>
        <li>Private institutions like schools, colleges, hospitals, and industrial facilities.</li>
      </ul>
      <p>These systems are suitable for any location with adequate rooftop space and exposure to sunlight.</p>`
    },
    {
      question: "How Much Roof Area is Required for a Grid-Connected Rooftop Solar PV System?",
      answer: `<p>Approximately 6–8 square meters of shadow-free area is needed to install a 1 kWp (kilowatt peak) Grid-Connected Rooftop Solar PV System.</p>`
    },
    {
      question: "Why is a Shadow-Free Area Required for Solar Modules?",
      answer: `<p>Solar modules require uninterrupted sunlight to generate maximum electricity. Shadows, even on a small part of a module, can significantly reduce energy output, leading to inefficiency and underutilization of the installed system capacity.</p>
      <p>Additionally, regular or intermittent shading can cause long-term damage to the modules. Prolonged exposure to shadows on certain cells or panels can shorten their lifespan, rendering them ineffective well before their standard operational life of over 25 years.</p>`
    },
    {
      question: "What Types of Roofs are Suitable for Rooftop Solar (RTS) Systems?",
      answer: `<p>Rooftop solar PV systems can be installed on any type of roof as long as it has sufficient load-bearing capacity to support the system. This includes:</p>
      <ul>
        <li>Flat roofs</li>
        <li>Sloped or pitched roofs</li>
        <li>Concrete roofs</li>
        <li>Metal or sheet roofs</li>
      </ul>
      <p>Proper structural assessment and design are essential to ensure the roof can safely accommodate the system.</p>`
    },
    {
      question: "How Much Energy Does a 1 kWp Solar Power Plant Generate Daily?",
      answer: `<p>On a clear, sunny day, a 1 kWp solar power plant can produce approximately 4 to 5 units of electricity per day (1 unit = 1 kWh).</p>`
    },
    {
      question: "Will the Rooftop Solar (RTS) System Generate the Same Amount of Energy Throughout the Year?",
      answer: `<p>No, the daily energy generation from an RTS system varies throughout the year. It depends on factors such as:</p>
      <ul>
        <li>Solar irradiance (availability of sunlight).</li>
        <li>Temperature and weather conditions.</li>
        <li>Seasonal changes and cloud cover.</li>
      </ul>
      <p>These factors fluctuate daily, leading to variations in energy output.</p>`
    },
    {
      question: "What Factors Affect Energy Generation from a Solar Power Plant?",
      answer: `<p>The energy generation of a solar power plant is influenced by several factors, including:</p>
      <ul>
        <li>Plant Location: Solar irradiance levels vary by geographic location.</li>
        <li>Quality of Equipment: High-quality components ensure better efficiency and reliability.</li>
        <li>Number of Sunshine Hours: Longer exposure to sunlight increases energy production.</li>
        <li>Workmanship: Proper installation and alignment ensure optimal system performance.</li>
        <li>PV Module Tilt Angle and Orientation: Correct tilt and orientation maximize sunlight absorption.</li>
        <li>Module Cleaning: Regular cleaning prevents dirt and debris from reducing efficiency.</li>
        <li>Operation and Maintenance (O&M) Activities: Routine inspections and timely repairs ensure sustained performance.</li>
      </ul>`
    },
    {
      question: "Will I Get the Same Annual Energy from the RTS for All 25 Years?",
      answer: `<p>No, the energy generation from a rooftop solar system will not remain the same over 25 years. Over time, solar modules experience degradation due to prolonged exposure to sunlight and environmental factors. This degradation leads to a gradual decrease in their efficiency and power output. Typically, solar modules lose about 0.5% to 1% of their efficiency per year, resulting in a gradual reduction in energy generation over the system's lifetime.</p>`
    },
    {
      question: "What Are the Advantages of Installing a Grid-Connected Rooftop Solar PV Power Plant?",
      answer: `<ol>
        <li>Savings on Electricity Bills: The consumer reduces their electricity costs by generating their own power.</li>
        <li>Utilization of Available Roof Space: No need for additional land, as the system uses existing roof space.</li>
        <li>Low Gestation Period: Quick installation and minimal time required to start generating power.</li>
        <li>No Need for Additional Transmission and Distribution (T&D) Lines: Power is generated and consumed locally, reducing infrastructure requirements.</li>
        <li>Reduction in T&D Losses: With power consumption and generation located in the same area, T&D losses are minimized.</li>
        <li>Improvement in Grid Voltages: The system helps stabilize voltage levels, especially at the tail-end of the grid, and reduces system congestion.</li>
        <li>Long-Term Energy and Ecological Security: By reducing reliance on conventional energy sources, it decreases carbon emissions and supports sustainability.</li>
        <li>Better Management of Daytime Peak Loads: Utilities (DISCOMs) can better manage peak electricity demand during the day.</li>
        <li>Compliance with Renewable Purchase Obligations (RPOs): Helps meet RPO targets set for obligated entities (such as utilities and large consumers).</li>
      </ol>`
    },
    {
      question: "What is the Average Cost of Grid-Connected Rooftop Solar Systems?",
      answer: `<p>For smaller capacity grid-connected rooftop solar systems, the cost is approximately Rs 60,000 per kW. For larger systems, the cost per kW tends to be lower due to economies of scale.</p>`
    },
    {
      question: "What Are the Subsidies/Capital Support Available from the Government of India for Residential Consumers?",
      answer: `<p>Under the PM Surya Ghar: Muft Bijli Yojana, the Government of India offers the following subsidies for residential consumers:</p>
      <ul>
        <li>Rs 30,000 per kW for the first 2 kW of the system.</li>
        <li>Rs 18,000 per kW for additional capacity up to 3 kW.</li>
        <li>A total subsidy of Rs 78,000 for systems larger than 3 kW.</li>
      </ul>
      <p>These subsidies are aimed at promoting solar energy adoption among residential users by reducing the initial installation cost.</p>`
    },
    {
      question: "What Are the Subsidies for Group Housing Societies/Resident Welfare Associations (GHS/RWA) from the Government of India?",
      answer: `<p>Under the PM Surya Ghar: Muft Bijli Yojana, the Government of India provides the following subsidies for Group Housing Societies (GHS) and Resident Welfare Associations (RWA):</p>
      <ul>
        <li>Rs. 18,000 per kW for common facilities, which can include applications such as electric vehicle (EV) charging stations.</li>
        <li>The subsidy is available for systems up to a 500 kW capacity, with an allocation of 3 kW per house in the society or association.</li>
        <li>The total subsidy limit includes the capacity of individual rooftop systems installed by the residents within the GHS/RWA.</li>
      </ul>`
    },
    {
      question: "Is There Any Subsidy/Support for Rooftop Solar Systems from the Delhi Government?",
      answer: `<p>Yes, under the Delhi Solar Energy Policy 2023, the Delhi Government offers additional support for rooftop solar systems, including:</p>
      <p>State Capital Subsidy: For residential customers, a capital subsidy of Rs. 2,000 per kW is provided, with a maximum subsidy of Rs. 10,000 per consumer.</p>
      <p>Generation-Based Incentives (GBI): Incentives based on the actual electricity generated by the solar system.</p>
      <ul>
        <li>Residential Consumers:
            <ul>
                <li>For systems up to 3 kW: INR 3 per kWh.</li>
                <li>For systems above 3 kW and up to 10 kW: INR 2 per kWh.</li>
            </ul>
        </li>
        <li>Group Housing Societies/Residential Welfare Associations:
            <ul>
                <li>For systems up to 500 kW (with a maximum of 10 kW per house): INR 2 per kWh.</li>
            </ul>
        </li>
        <li>Commercial and Industrial Consumers:
            <ul>
                <li>For the first 200 MW deployed: INR 1 per kWh.</li>
            </ul>
        </li>
      </ul>
      <p>These incentives aim to encourage both residential and commercial adoption of rooftop solar systems while supporting the generation of renewable energy in Delhi.</p>
      <p>These subsidies are provided in addition to the central government subsidies under schemes like the PM Surya Ghar: Muft Bijli Yojana.</p>`
    },
    {
      question: "How Should I Evaluate Vendors Offering Rooftop Solar (RTS) Systems? What Are the Main Points of Consideration?",
      answer: `<p>When selecting a vendor for a rooftop solar system, the price is important but should not be the sole deciding factor. Consider the following key points:</p>
      <ol>
        <li>Price of the Offered System: Compare prices of different vendors but ensure that the pricing is reasonable for the quality and services provided.</li>
        <li>Warranties of System and Components: Check the warranty offered for the system and its components (e.g., solar panels, inverter). A longer warranty period often indicates better product reliability.</li>
        <li>Energy Generation Estimates and Guarantees: Request a detailed energy generation estimate, and ensure the vendor provides a performance guarantee to meet expected generation levels.</li>
        <li>Service Backup and Support: Evaluate the vendor's after-sales service arrangements, including maintenance, repairs, and response times, especially in your area.</li>
        <li>Reference Installations and Vendor Track Record: Ask for references from previous installations and get feedback from their customers regarding system performance and the quality of service provided.</li>
      </ol>
      <p>By considering these factors, you can ensure that you choose a reliable and capable vendor for your rooftop solar system.</p>`
    },
    {
      question: "What is Net Metering?",
      answer: `<p>Net metering is a system where the excess solar energy generated by a rooftop solar system is fed back into the grid. The energy exported to the grid is then deducted from the energy the consumer imports from the grid, subject to certain conditions.</p>
      <p>The consumer is billed only for the net energy imported from the grid, which is the difference between the energy consumed from the grid and the energy exported to it. This allows consumers to offset their electricity bills by utilizing the energy they generate but do not immediately use.</p>`
    },
    {
      question: "What is Gross Metering?",
      answer: `<p>Gross Metering refers to a methodology in which the entire electricity generated by a rooftop or ground-mounted Solar PV System installed at the consumer's premises is delivered to the distribution system of the distribution licensee.</p>
      <p>In this system, the entire output of the solar power generation is exported to the grid without any consumption being deducted at the consumer's end. Unlike net metering, where excess energy is credited to the consumer's account, gross metering involves the consumer delivering all generated power directly to the grid, typically without any compensation for the self-consumption of energy. The consumer may still pay for the electricity drawn from the grid, but no credit is given for the solar power they generate.</p>`
    },
    {
      question: "What is Group Net Metering?",
      answer: `<p>In a Group Net Metering arrangement, energy produced by a collectively owned solar PV system is fed into the grid. The solar energy generated is then credited to the electricity bills of each participating consumer on a pro-rata basis, depending on their share of the collective system.</p>
      <p>The list of buildings eligible for GNM must be of Same Consumer i.e. having Same Name and must be situated in DISCOM Licensee area for setting-off of their consumption.</p>`
    },
    {
      question: "What is Virtual Net Metering?",
      answer: `<p>Virtual Net Metering refers to an arrangement where the entire energy generated or injected from a renewable energy system (such as solar) or a Battery Energy Storage System (BESS), which is charged using renewable energy, is exported to the grid through a renewable energy meter or a gross meter.</p>
      <p>The exported energy is then adjusted in multiple electricity service connections of participating consumers. These consumers are located within the same distribution licensee's area of supply.</p>
      <p>This system allows multiple consumers to share the benefits of the energy produced by a single renewable energy installation, even if the consumers are not physically located at the same site. It's an effective model for enabling distributed renewable energy access, particularly in areas where individual consumers may not have suitable roof space or resources for direct installation.</p>`
    },
    {
      question: "What Are the Different Business Models Under Which I Can Install Grid-Connected Rooftop Solar PV Power Plants?",
      answer: `<p>There are two main business models for installing Grid-Connected Rooftop Solar PV Power Plants:</p>
      <p><strong>1. CAPEX Model (Capital Expenditure Model):</strong></p>
      <ul>
        <li>In this model, the consumer owns the system and bears the full cost of the installation.</li>
        <li>The consumer benefits from the energy generated by the system and saves on electricity bills.</li>
        <li>The consumer is also responsible for the operation and maintenance (O&M) of the system.</li>
      </ul>
      <p><strong>2. RESCO Model (Renewable Energy Service Company Model):</strong></p>
      <ul>
        <li>In the RESCO model, the system is owned by a third-party developer (the RESCO company).</li>
        <li>The consumer purchases the energy generated by the system by paying a pre-decided tariff on a monthly basis as per a Power Purchase Agreement (PPA).</li>
        <li>The developer is responsible for the O&M of the system throughout its lifetime (typically 25 years).</li>
      </ul>
      <p>Both models offer different financial and operational responsibilities, depending on whether the consumer prefers to own the system or pay for the energy generated without upfront investment.</p>`
    },
    {
      question: "How Can I Apply for Installation of a Solar Rooftop System?",
      answer: `<ul>
        <li>Residential Consumers and Group Housing Societies: To avail the Central subsidy under the PM Suryaghar Scheme, they must apply through the GoI online portal at https://www.pmsuryaghar.gov.in/.</li>
        <li>Other Consumers (not eligible for Central subsidy): They can apply for installation through the online portal of their respective DISCOMs (Distribution Companies).</li>
      </ul>
      <p>The application process will guide you through the necessary steps to apply for a rooftop solar system, depending on your eligibility for subsidies.</p>`
    },
    {
      question: "What are the processes involved in PM Suryaghar Scheme from application to subsidy receivable?",
      answer: `<ul>
        <li>Consumer Registration: Sign up to start your application journey</li>
        <li>Application Submission: Submit your Application</li>
        <li>Feasibility Approval: Check if your location is solar-ready</li>
        <li>Vendor Selection: Choose the best vendor for installation</li>
        <li>Work Start: Begin the installation process</li>
        <li>Solar Installation Details: Provide details for your Solar Rooftop Installation</li>
        <li>Project Inspection: DISCOM to inspect site for compliance</li>
        <li>Project Commissioning: DISCOM to certify your Solar Rooftop Installation</li>
        <li>Subsidy Request: Redeem your Subsidy</li>
        <li>Subsidy Disbursal: Subsidy Approval</li>
      </ul>`
    },
    {
      question: "What Kind of System Can Be Installed in a Group Housing Society (GHS)?",
      answer: `<p>In a Group Housing Society (GHS), several common rooftops can be utilized to install a rooftop solar PV system. The energy generated from these systems is primarily used to offset the common electrical loads of the society, such as:</p>
      <ul>
        <li>Common lighting</li>
        <li>Lifts</li>
        <li>Water pumps</li>
        <li>Other shared facilities</li>
      </ul>
      <p>A Net Meter is provided against the Single Point Delivery (SPD) common meter of the society. This allows the energy generated by the solar system to be fed into the grid, and any excess energy is credited to the society's electricity bill.</p>
      <p>The GHS benefits from reduced monthly electricity expenses as the solar energy helps to lower the overall consumption from the grid.</p>`
    },
    {
      question: "What is the Minimum Warranty Period Envisaged Under the PM Sury Ghar Scheme?",
      answer: `<p>Under the scheme, the minimum warranty requirements for various components of the solar power plant/system are as follows:</p>
      <p><strong>1. Solar PV Modules:</strong></p>
      <ul>
        <li>The modules must be warranted for their output peak watt capacity, which should not be less than:
            <ul>
                <li>90% of the rated capacity at the end of 12 years.</li>
                <li>80% of the rated capacity at the end of 25 years.</li>
            </ul>
        </li>
      </ul>
      <p><strong>2. Other Components (including mechanical structures, electrical works, inverters, charge controllers, distribution boards, digital meters, switch gear, storage batteries, etc.):</strong></p>
      <ul>
        <li>These must be warranted against any manufacturing, design, or installation defects for a minimum period of 5 years.</li>
      </ul>
      <p>These warranty periods ensure that the solar power system maintains its performance and reliability over its expected lifespan.</p>`
    },
    {
      question: "What Are the O&M Aspects of a Grid-Connected Rooftop Solar PV System?",
      answer: `<p>Solar PV systems require minimal maintenance compared to most other power-generating technologies. However, regular Operation and Maintenance (O&M) activities are crucial to optimize energy yield and maximize the system's lifespan. Some key O&M tasks include:</p>
      <p><strong>1. Module Cleaning:</strong></p>
      <ul>
        <li>Periodic cleaning is necessary to remove dust, bird droppings, and other debris, which can reduce power generation.</li>
        <li>The cleaning frequency depends on local conditions, such as dust levels, bird activity, and air pollution.</li>
      </ul>
      <p><strong>2. Other Maintenance Tasks:</strong></p>
      <ul>
        <li>Checking module connection integrity: Ensuring that connections are secure and functional.</li>
        <li>Inspecting junction boxes / string combiner boxes: Verifying that the electrical connections are intact.</li>
        <li>Inspecting the mechanical integrity of mounting structures: Ensuring that the structures are stable and secure.</li>
        <li>Tightening cable connections: Checking and tightening any loose cables.</li>
        <li>Replacing blown fuses: Identifying and replacing any blown fuses.</li>
        <li>Repairing lightning damage: Addressing any issues caused by lightning strikes.</li>
        <li>Repairing equipment damaged by intruders or during cleaning: Ensuring that the system remains intact after handling or external disturbances.</li>
      </ul>
      <p>These O&M activities are essential for maintaining the system's efficiency and prolonging its operational life.</p>`
    },
    {
      question: "What Is the Gross Potential of Solar Power in the Country?",
      answer: `<p>India has vast solar energy potential due to its geographical location and high levels of solar radiation. The total energy incident on India's land area is approximately 5,000 trillion kWh per year, with most parts of the country receiving about 3-5 kWh per square meter per day.</p>
      <p>Based on the availability of land and solar radiation, the gross potential of solar power in India has been assessed to be around 750 GW. This immense potential highlights the country's capacity to harness solar energy to meet its growing energy demands and contribute to sustainable development.</p>`
    },
    {
      question: "What Is the Potential for Rooftop Solar Power in the Country?",
      answer: `<p>The National Institute of Solar Energy (NISE), an autonomous institute under the Ministry of New and Renewable Energy, has estimated that the potential for Grid-Connected Rooftop Solar (RTS) in India is around 43 GW.</p>
      <p>This potential reflects the capacity to harness solar energy from rooftops of residential, commercial, and industrial buildings across the country, contributing significantly to India's renewable energy goals.</p>`
    },
    {
      question: "What Is the Potential for Rooftop Solar Power in Delhi?",
      answer: `<p>Delhi has an estimated solar energy potential of 2500 MWp for rooftop solar power systems. This potential represents the capacity to harness solar energy from rooftops across the city, contributing significantly to its renewable energy targets and reducing dependence on conventional sources of power.</p>`
    },
    {
      question: "What Are the Innovative Business Models Proposed Under the Delhi Solar Energy Policy 2023?",
      answer: `<p>The Delhi Solar Energy Policy 2023 introduces several innovative business models to expand the adoption of solar energy. These include:</p>
      <p><strong>1. Community Solar:</strong></p>
      <ul>
        <li>This model enables consumers who do not have roof space to benefit from rooftop solar power by participating in community solar projects. The energy generated from these projects can be shared among participants, providing access to solar energy without needing to install panels on individual rooftops.</li>
      </ul>
      <p><strong>2. Peer-to-Peer Trading:</strong></p>
      <ul>
        <li>This model allows consumers with excess solar electricity to sell the surplus power to other consumers who have limited or no access to solar energy. It fosters a decentralized electricity market and enables consumers to monetize their excess generation.</li>
      </ul>
      <p><strong>3. Hybrid RESCO (Renewable Energy Service Company):</strong></p>
      <ul>
        <li>For consumers who have roof space but cannot afford the upfront investment for rooftop solar installation, the Hybrid RESCO model offers a solution. Under this model, a third-party developer installs and owns the system, while the consumer pays for the energy generated at a pre-agreed tariff.</li>
      </ul>
      <p>These business models aim to make solar energy more accessible to a wider range of consumers and contribute to the growth of renewable energy in Delhi.</p>`
    },
    {
      question: "Is It Necessary to Choose a Vendor Empanelled Under PM Surya Ghar Yojna to Install a Solar Rooftop System?",
      answer: `<ul>
        <li>For Consumers Availing Central Government Subsidy Under PM Surya Ghar Yojna:
            <p>It is mandatory to choose a vendor that is empanelled with the PM Surya Ghar Portal to avail the central subsidy under the scheme.</p>
        </li>
        <li>For Other Consumers (Not Availing PM Surya Ghar Subsidy):
            <p>It is not mandatory to choose a vendor from the PM Surya Ghar Portal. Consumers can select any vendor of their choice for the installation of the solar rooftop system.</p>
        </li>
      </ul>
      <p>Additionally, Delhi State Subsidy and Generation-Based Incentive (GBI) are available for all net-metered installations, regardless of the vendor chosen, as long as they fall within the respective categories. Therefore, consumers have the freedom to make their own choice of vendor.</p>`
    },
    {
      question: "What is the meaning of Renewable Energy Projects?",
      answer: `<p>"Renewable Energy Projects" means a project generating grid quality electricity from Renewable Energy Sources excluding conventional power plants.</p>`
    },
    {
      question: "What are the Renewable Energy Sources?",
      answer: `<p>"Renewable Energy Sources" (RES) means:</p>
      <ol type="a">
        <li>solar radiation, wind, small/mini hydro, biomass, biofuels, biogas, landfill gas, sewage gas, geothermal energy, ocean energy, and combinations thereof;</li>
        <li>any other sources of energy as may be notified by the Central Government from time to time;</li>
        <li>any combination, as may be notified by the Central Government, of the sources specified in sub-clauses (a) or (b) with other sources of energy.</li>
      </ol>`
    },
    {
      question: "What is the meaning of 'Solar Power Producer'?",
      answer: `<p>"Solar Power Producer" means an entity, which owns facilities to generate electric power for sale to DISCOM /Licensees/to third party/captive use.</p>`
    },
    {
      question: "What is the meaning of Tariff?",
      answer: `<p>"Tariff" means the schedule of charges for generation, transmission, wheeling and supply of electricity together with terms and conditions for application thereof.</p>`
    },
    {
      question: "What is meaning of 'COD'?",
      answer: `<p>"COD" means Commercial Operation Date, i.e. the date when the Power Plant gets commissioned as per rules/provisions;</p>`
    },
    {
      question: "What is Interconnection Line?",
      answer: `<p>Interconnection Line refers to the Transmission/Distribution Line that connects the Generating Plant Sub-station or Pooling Sub-station of the Developer or Power Producer to the Receiving Sub-Station of the Inter-State Transmission System (ISTS), State Power Transmission company or Distribution Companies (DISCOMs).</p>
      <p>This line facilitates the flow of electricity from the generating plant to the grid, enabling the power generated to be transmitted or distributed to the intended consumers or connected systems within the state's infrastructure.</p>`
    },
    {
      question: "What is Inter-Connection Point?",
      answer: `<p>Inter-Connection Point refers to the point at which electricity produced from a Renewable Energy (RE) generating station is injected into the grid. This point is typically located at:</p>
      <ul>
        <li>An Extra High Voltage (EHV) substation of the Transmission Licensee, or</li>
        <li>A High Voltage (HV) substation of the Distribution Licensee, depending on the specific setup.</li>
      </ul>
      <p>It is the designated location where the generated power is transferred from the renewable energy source to the transmission or distribution network for further distribution to consumers.</p>`
    },
    {
      question: "What is the Inter-State Transmission System (ISTS)?",
      answer: `<p>ISTS stands for Inter-State Transmission System. It refers to the network of high-voltage transmission lines and infrastructure that facilitates the transfer of electricity across state boundaries within a country. The ISTS enables the interconnection of power plants to the broader national grid and allows electricity to be transmitted from one state to another, ensuring a reliable and balanced power supply across regions.</p>`
    },
    {
      question: "What is the Pooled Cost of Power Purchase?",
      answer: `<p>Pooled Cost of Power Purchase refers to the weighted average price at which the distribution licensee has purchased electricity in the previous year. This includes the cost of electricity from all energy suppliers, such as:</p>
      <ul>
        <li>The cost of self-generation (if any),</li>
        <li>Long-term power purchases, and</li>
        <li>Power purchased from other suppliers.</li>
      </ul>
      <p>However, it excludes:</p>
      <ul>
        <li>The cost of short-term power purchases, and</li>
        <li>The cost of power purchased from renewable energy sources.</li>
      </ul>
      <p>This calculation provides an overall average cost that the distribution licensee has paid for electricity procurement, which helps in determining tariffs and overall electricity pricing for consumers.</p>`
    },
    {
      question: "What is a Solar Thermal Power Plant?",
      answer: `<p>A Solar Thermal Power Plant refers to a power plant that uses sunlight through Concentrated Solar Power (CSP) technology to generate heat or steam, which is then used to produce electricity. CSP technology operates on two main principles:</p>
      <ol>
        <li>Line Focus: In this method, parabolic mirrors or troughs concentrate sunlight onto a central receiver, which absorbs the heat and transfers it to a fluid, creating steam for electricity generation.</li>
        <li>Point Focus: This method uses mirrors or lenses to concentrate sunlight onto a single focal point, where the heat is absorbed and used to generate steam or heat for power production.</li>
      </ol>
      <p>Solar Thermal Power Plants use this heat instead of direct electricity generation from photovoltaic cells (like in solar PV systems), making them suitable for large-scale energy production, often in regions with high solar radiation.</p>`
    },
    {
      question: "What is the meaning of banking wrt Solar Plant?",
      answer: `<p>Banking refers to the process where surplus green energy (generated from renewable energy sources like solar or wind) is injected into the grid by RE plant. This energy is credited with the distribution licensee, meaning the excess electricity generated by the consumer is stored or "banked" in the grid.</p>
      <p>The consumer can later draw back this stored energy, typically during times when their own renewable generation is insufficient, such as during cloudy days for solar systems. However, there may be charges associated with this energy withdrawal to compensate for any additional costs incurred by the distribution system. The banking mechanism allows consumers to balance their energy supply and demand while supporting the integration of renewable energy into the grid.</p>`
    },
    {
      question: "What is Captive Generating Plant (CGP)?",
      answer: `<p>A Captive Generating Plant (CGP) refers to a power plant set up under Section 9 of the Electricity Act, 2003 by any individual or entity to generate electricity primarily for its own use.</p>
      <p>The key characteristics of a CGP include:</p>
      <ol>
        <li>It is primarily intended to meet the energy needs of the plant owner or a designated group, such as the members of a cooperative society or an association of persons.</li>
        <li>The plant must comply with the conditions specified under the Electricity Act, 2003 and the associated rules, including the requirement that the energy generated should be predominantly consumed by the plant owner or its members.</li>
      </ol>
      <p>CGPs are commonly used by large industrial consumers or group housing societies to generate their own electricity, reduce reliance on the grid, and potentially lower energy costs.</p>`
    },
    {
      question: "What is the Open Access?",
      answer: `<p>Open Access refers to the non-discriminatory access granted to users for utilizing the transmission and/or distribution system (or associated facilities) owned by a distribution licensee or a transmission licensee. This allows various entities, such as:</p>
      <ul>
        <li>Consumers</li>
        <li>Generators</li>
        <li>Licensees</li>
      </ul>
      <p>to use these transmission lines or distribution systems for transporting electricity, under the conditions specified by the Appropriate Commission.</p>
      <p><strong>Key Points:</strong></p>
      <ol>
        <li><strong>Non-discriminatory:</strong> All users are treated fairly, without bias or preference, ensuring equitable access.</li>
        <li><strong>Regulated by the Commission:</strong> The regulations governing Open Access are set by the appropriate regulatory authority (e.g., the Central Electricity Regulatory Commission (CERC) or State Electricity Regulatory Commissions (SERC)).</li>
        <li><strong>Purpose:</strong> Open Access enables consumers and generators to buy electricity from the most efficient or cost-effective sources, even if they are located in different areas, by utilizing the existing infrastructure for power transmission and distribution.</li>
      </ol>
      <p>Open Access is crucial for promoting competition in the electricity market, allowing consumers and generators more flexibility and options for sourcing their electricity.</p>`
    },
    {
      question: "Define the Green Energy Open Access Consumer?",
      answer: `<p>A Green Energy Open Access Consumer is a person or entity that meets the following criteria:</p>
      <ol>
        <li>Contract Demand or Sanctioned Load: The consumer must have a contract demand or sanctioned load of 100 kW or more, either through a single connection or multiple connections aggregating to 100 kW or more. These connections must be at 11 kV or above.</li>
        <li>Location: The consumer should be located within the electricity service area of a single distribution licensee.</li>
        <li>Source of Electricity: The consumer is supplied with electricity from green energy sources, which can include:
            <ul>
                <li>A Captive Generation Plant (CGP) owned by the consumer or a group.</li>
                <li>Electricity sourced from licensed suppliers or the Government, or from an entity engaged in the business of supplying electricity as per the Electricity Act, 2003.</li>
            </ul>
        </li>
        <li>Premises Connection: The consumer's premises must be connected for receiving green energy from the distribution licensee, the Government, or another authorized supplier.</li>
        <li>No Load Limitation: There is no load limitation for setting up green energy projects for captive use, meaning the consumer can set up a green energy system regardless of their contract demand/sanctioned load with the distribution company when using the energy for their own consumption.</li>
      </ol>`
    },
    {
      question: "What is the meaning of Standby Arrangement by Discom?",
      answer: `<p>Standby Arrangement refers to a backup supply of electricity provided by the distribution licensee to an Open Access consumer when the consumer is unable to procure or schedule power from their primary generating sources. This situation typically occurs due to outages or disruptions in the operation of the generating sources, transmission assets, or other related infrastructure.</p>
      <h3>Key Points:</h3>
      <ul>
        <li><strong>Backup Power:</strong> Standby arrangements ensure that the consumer continues to have a reliable power supply, even if their usual green energy sources are unavailable.</li>
        <li><strong>Role of Distribution Licensee:</strong> The distribution licensee is responsible for providing this backup power to the consumer under the conditions of the Standby Arrangement.</li>
        <li><strong>Context:</strong> It is most relevant for Green Energy Open Access consumers who primarily depend on renewable energy sources or captive generation but need a safety net for situations where their regular power supply might be interrupted (e.g., generator outages, grid failures, etc.).</li>
      </ul>
      <p>This arrangement ensures that the consumer's electricity supply remains uninterrupted while mitigating the risk of disruptions.</p>`
    },
    {
      question: "What is the meaning of Standby Charges to Open Access consumers?",
      answer: `<p>Standby Charges refer to the fees that Open Access consumers are required to pay to the distribution licensee for providing a standby arrangement. This arrangement comes into play when the consumer is unable to procure or schedule power from their usual green energy sources due to outages or disruptions in the generation system, transmission infrastructure, or other related assets.</p>
      <h3>Key Points:</h3>
      <ul>
        <li><strong>Purpose:</strong> Standby charges are meant to cover the cost of providing backup power from the distribution licensee when the consumer's primary energy sources are unavailable.</li>
        <li><strong>Trigger Events:</strong> The charges apply when the consumer's usual sources of green energy (such as a renewable energy system or captive generation plant) experience outages or are otherwise unable to provide power due to issues like generator failures or transmission problems.</li>
        <li><strong>Consumer Responsibility:</strong> The consumer must pay these charges for the additional service of ensuring that power is available during disruptions, ensuring the continuity of their electricity supply.</li>
      </ul>
      <p>These charges ensure that the distribution licensee can offer backup power and maintain the stability of the system during unforeseen events.</p>`
    },
    {
      question: "What is the meaning of Wheeling",
      answer: `<p>Wheeling refers to the process where the distribution system (or sometimes the transmission system) and its associated facilities are used by an entity (other than the owner of the system) to transport electricity. This process is carried out for the conveyance of electricity, and the person using the system must pay charges for this service.</p>
      <h3>Key Points:</h3>
      <ul>
        <li><strong>Usage of System:</strong> Wheeling involves using the existing transmission or distribution infrastructure, owned by a licensee (either a transmission licensee or a distribution licensee), to move electricity.</li>
        <li><strong>Payment of Charges:</strong> The person using the system must pay the charges for this service. These charges are typically determined under Section 62 of the Electricity Act, which governs tariff setting and wheeling agreements.</li>
        <li><strong>Context:</strong> Wheeling is often used in scenarios where electricity is generated from renewable sources and needs to be transported to a different location, such as for Open Access consumers or captive power plants.</li>
      </ul>
      <p>Essentially, wheeling enables the transfer of electricity over a network that is not owned by the entity generating the power, ensuring the generation and consumption locations can be separate.</p>`
    }
  ];

  const filteredFaqData = faqData.filter(item =>
    item.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.answer.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-green-50">
      {/* Header */}
      <div className="w-full bg-gradient-to-r from-imp-text to-orange-300 py-10 mb-10">
        <div className="container xl:max-w-7xl mx-auto px-4 text-center">
          <motion.h1
            className="text-4xl sm:text-5xl font-bold text-white mb-4"
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.6 }}
          >
            Solar Rooftop FAQ
          </motion.h1>
          <p className="text-lg text-white max-w-2xl mx-auto">
            Comprehensive guide to grid-connected rooftop solar PV systems, subsidies, installation, and more.
          </p>

        </div>
      </div>
      <div className="max-w-4xl mx-auto">





        {/* Search Bar */}
        <div className="mb-8">
          <div className="relative">
            <input
              type="text"
              placeholder="Search questions or keywords..."
              className="w-full p-4 pl-12 rounded-xl border border-gray-200 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <svg
              className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </div>
          {searchTerm && (
            <p className="text-sm text-gray-500 mt-2">
              Found {filteredFaqData.length} results for "{searchTerm}"
            </p>
          )}
        </div>

        {/* FAQ Items */}
        <div className="space-y-4">
          {filteredFaqData.map((item, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-md overflow-hidden transition-all duration-300 hover:shadow-lg"
            >
              <button
                className="w-full flex justify-between items-center p-6 text-left focus:outline-none hover:bg-blue-50 transition-colors duration-200"
                onClick={() => toggleItem(index)}
              >
                <h3 className="text-lg font-semibold text-gray-800 pr-4">
                  {item.question}
                </h3>
                <span className="flex-shrink-0">
                  {openItems[index] ? (
                    <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                    </svg>
                  ) : (
                    <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  )}
                </span>
              </button>

              <div
                className={`px-6 overflow-hidden transition-all duration-300 ${openItems[index] ? 'max-h-screen pb-6' : 'max-h-0'
                  }`}
              >
                <div
                  className="text-gray-600 space-y-3 prose prose-sm max-w-none"
                  dangerouslySetInnerHTML={{ __html: item.answer }}
                />
              </div>
            </div>
          ))}
        </div>

        {/* Additional Resources */}
        <div className="mt-12 bg-blue-50 rounded-xl p-6 border border-blue-100">
          <h3 className="text-xl font-bold text-gray-800 mb-4">Need More Information?</h3>
          <p className="text-gray-600 mb-4">
            For detailed technical specifications, subsidy applications, or vendor selection, please visit the official PM Surya Ghar portal.
          </p>
          <div className="flex flex-wrap gap-4">
            <a
              href="https://www.pmsuryaghar.gov.in/"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors duration-300"
            >
              Visit PM Surya Ghar Portal
              <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg>
            </a>
            <button
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
              className="inline-flex items-center bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors duration-300"
            >
              Back to Top
              <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Faq;