import React from 'react';

const Faq = () => {

  return (
    <>
     
      {/* Page Header */}
      <div className="w-full bg-gradient-to-r from-blue-600 to-blue-400 py-20 mb-12 text-center relative overflow-hidden">
        <div className="container mx-auto px-4">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-3 animate-slideDown">
            FAQ
          </h1>
          <nav aria-label="breadcrumb">
            {/* Breadcrumb (optional) */}
          </nav>
        </div>
      </div>

      {/* FAQ Content */}
      <div className="container mx-auto px-4 py-10">
        <h2 className="text-2xl font-semibold mb-4">
          Q1. What is a Grid Connected Rooftop Solar PV System?
        </h2>
        <p className="mb-2 text-gray-700 leading-relaxed">
          In grid-connected rooftop or small solar photovoltaic (SPV) systems,
          the direct current (DC) electricity generated by the SPV panels is
          converted into alternating current (AC) using a Power Conditioning
          Unit (PCU). This AC power is then supplied to the grid.
        </p>
        <p className="mb-6 text-gray-700 leading-relaxed">
          During daylight hours, these SPV systems generate electricity, which
          is primarily used to power local loads. Any surplus electricity is fed
          back into the grid, provided it is operational. When solar power
          generation is insufficient—such as during cloudy weather—the required
          electricity for local loads is drawn from the grid.
        </p>

        <h2 className="text-2xl font-semibold mb-4">
          Q2. What are the Main Components of a Grid-Connected Rooftop Solar PV
          System?
        </h2>

        <div className="space-y-4 text-gray-700 leading-relaxed">
          <div>
            <p className="font-semibold">1. Solar PV Modules/Panels:</p>
            <p>
              These modules convert sunlight into direct current (DC)
              electricity. They come in various technologies such as crystalline
              silicon, thin-film silicon, CIGS, CdTe, and HIT, with crystalline
              silicon being the most commonly used in rooftop systems. Multiple
              panels are connected to form arrays, tailored to the system's
              desired capacity.
            </p>
          </div>

          <div>
            <p className="font-semibold">2. Inverter:</p>
            <p>
              The inverter plays a critical role by converting the variable DC
              output from the solar panels into alternating current (AC) power,
              which can be used by appliances or fed into the grid. It also
              ensures synchronization with the grid to facilitate seamless power
              injection.
            </p>
          </div>

          <div>
            <p className="font-semibold">3. Module Mounting Structure:</p>
            <p>
              This structure provides sturdy support to the solar panels
              throughout their lifespan and withstands various weather
              conditions. For rooftop systems, these structures are usually
              fixed at specific angles and orientations but can also be equipped
              with trackers that follow the Sun to maximize energy capture.
            </p>
          </div>

          <div>
            <p className="font-semibold">4. Bi-directional Meters:</p>
            <p>
              These meters, also known as net meters, monitor the energy flow.
              They track the amount of electricity generated and fed into the
              grid by the solar PV system and the electricity drawn from the
              grid when needed.
            </p>
          </div>

          <div>
            <p className="font-semibold">5. Balance of System (BoS):</p>
            <p>
              This includes all additional components required for the system's
              functioning, such as cables, switchboards, junction boxes,
              earthing systems, circuit breakers, fuses, and lightning
              protection systems. These elements ensure safety, efficiency, and
              reliability of the overall system.
            </p>
          </div>
        </div>

        {/* Example last item */}
        <h2 className="text-2xl font-semibold mt-10 mb-4">
          Q48. What is the meaning of Wheeling?
        </h2>
        <p className="mb-4 text-gray-700 leading-relaxed">
          Wheeling refers to the process where the distribution system (or
          sometimes the transmission system) and its associated facilities are
          used by an entity (other than the owner of the system) to transport
          electricity. This process is carried out for the conveyance of
          electricity, and the person using the system must pay charges for this
          service.
        </p>
        <h3 className="text-xl font-semibold mb-2">Key Points:</h3>
        <ul className="list-disc list-inside text-gray-700 space-y-2">
          <li>
            <span className="font-semibold">Usage of System:</span> Wheeling
            involves using the existing transmission or distribution
            infrastructure, owned by a licensee (either a transmission licensee
            or a distribution licensee), to move electricity.
          </li>
          <li>
            <span className="font-semibold">Payment of Charges:</span> The
            person using the system must pay the charges for this service. These
            charges are typically determined under Section 62 of the Electricity
            Act, which governs tariff setting and wheeling agreements.
          </li>
          <li>
            <span className="font-semibold">Context:</span> Wheeling is often
            used in scenarios where electricity is generated from renewable
            sources and needs to be transported to a different location, such as
            for Open Access consumers or captive power plants.
          </li>
        </ul>
        <p className="mt-4 text-gray-700 leading-relaxed">
          Essentially, wheeling enables the transfer of electricity over a
          network that is not owned by the entity generating the power, ensuring
          the generation and consumption locations can be separate.
        </p>
      </div>
    </>
  );
};

export default Faq;
