import React from 'react';
import { motion } from 'framer-motion';

const RooftopSolar = () => {
  return (
    <>
      {/* Page Header Start */}
      <div className="w-full bg-gradient-to-r from-imp-text to-orange-300 py-10 mb-10">
        <div className="container xl:max-w-7xl mx-auto px-4 text-center">
          <motion.h1
            className="text-4xl sm:text-5xl font-bold text-white mb-4"
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.6 }}
          >
            Rooftop Solar
          </motion.h1>
       
        </div>
      </div>
      {/* Page Header End */}

     <div className="container max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div className="space-y-6">
    <p>
      The sun shines tirelessly throughout the day, providing a vast source of energy. Imagine harnessing this
      abundant power to energize your residential and commercial spaces year-round. India benefits from consistent
      sunlight throughout the year, which unfortunately also means higher electricity usage due to constant reliance
      on fans, coolers, air conditioners, and refrigerators, leading to hefty electricity bills. Unpredictable power
      outages further force reliance on costly and unreliable grid electricity.
    </p>

    <p>
      Transitioning to a solar rooftop system enables you to tap into the sun&apos;s power and enjoy clean,
      uninterrupted electricity at a significantly reduced cost. At Solar Radian, we recognize India’s ideal
      conditions for solar energy. The nearly year-round sunshine is perfect for solar installations, allowing for
      substantial savings on electricity and reduced dependence on the grid.
    </p>

    <p>
      Solar panels, consisting of photovoltaic (PV) cells, convert light into electrical energy. These PV cells,
      made of P-N junctions, use light (photons) to excite electrons, moving them from the valence band to the
      conduction band, which generates electric current.
    </p>

    <p>
      Many states in India have robust policies supporting residential solar rooftops, allowing you to use the
      power generated by your system for personal consumption. Utilize your roof space or unused land to install
      solar panels and begin generating your own electricity. This electricity can be fed back into the grid or
      stored in batteries for later use.
    </p>

    <p>
      Through net metering, excess solar power produced during the day can be credited back to your electricity
      bill. Depending on your energy needs and rooftop space, you may be able to reduce or completely eliminate
      your reliance on utility power, enjoying free solar energy indefinitely.
    </p>
  </div>

  <section className="space-y-4">
    <h2 className="text-2xl font-semibold">Benefits of Rooftop Solar Energy</h2>
    <ul className="list-disc list-inside space-y-2">
      <li>Electricity Bill Savings: Significant reductions in monthly energy expenses.</li>
      <li>Longevity: Solar power systems have a lifespan exceeding 25 years.</li>
      <li>Quick Return on Investment: Typical payback period ranges from 3–4 years.</li>
      <li>Energy Independence: Overcome rising electricity tariffs.</li>
      <li>Eco-Friendly: Lower your carbon footprint and contribute positively to the environment.</li>
      <li>Low Maintenance: With no moving parts, maintenance requirements are minimal.</li>
      <li>Adaptable Design: Easily upgrade your system to meet evolving energy demands.</li>
    </ul>
  </section>

  <section className="space-y-4">
    <h2 className="text-2xl font-semibold">Key Considerations for Installing Rooftop Solar</h2>

    <h3 className="text-xl font-semibold mt-4">Before Installation:</h3>
    <ul className="list-disc list-inside space-y-2">
      <li>Ensure your roof or land receives ample sunlight throughout most of the day.</li>
      <li>Have your property assessed by a professional solar company to evaluate shading, installation capacity, and energy production.</li>
      <li>Understand the total costs, potential savings, and any tax benefits associated with solar energy.</li>
      <li>Discuss and document guarantees and warranties for all components, workmanship, and overall system performance.</li>
      <li>Choose qualified and reputable installers or suppliers, and determine the appropriate system size and quality within your budget.</li>
      <li>Select high-quality mounting structures and hardware for durability and longevity (25–30 years).</li>
      <li>Agree on the specifications of solar components, materials, and payment terms with your installer.</li>
      <li>Review required permits and approvals with your installer.</li>
    </ul>

    <h3 className="text-xl font-semibold mt-4">During Installation:</h3>
    <ul className="list-disc list-inside space-y-2">
      <li>Ensure there is adequate access for workers and materials.</li>
      <li>Confirm that materials and components are delivered with necessary documentation.</li>
      <li>Follow safety protocols during the handling and placement of solar components.</li>
      <li>Verify that the materials and equipment conform to the contract specifications.</li>
      <li>Ensure civil foundations are properly finished, plastered, and cured.</li>
      <li>Securely install all hardware to avoid damage from improperly fitted panels.</li>
      <li>Properly secure each panel with fasteners and use HDPE pipes for cabling. Tag, clamp, and dress cables on walls and structures.</li>
      <li>Ensure all electrical connections are secure and properly identified.</li>
      <li>Connect all structures and components to an earthing system where required, consulting an expert for smaller systems.</li>
    </ul>

    <h3 className="text-xl font-semibold mt-4">Post Installation:</h3>
    <ul className="list-disc list-inside space-y-2">
      <li>Obtain all guarantee and warranty certificates, system test reports, energy meter test reports, and relevant permits or documents related to incentives and subsidies.</li>
      <li>Keep the contact information of your installer handy.</li>
      <li>Regularly clean the solar panels to maintain optimal efficiency and performance. Avoid dust, leaves, or bird droppings accumulating on the panels.</li>
      <li>Use clean water for panel cleaning and perform this task before 8 AM or after 6 PM to avoid disrupting energy production.</li>
      <li>Contact your installer or maintenance provider for any issues.</li>
      <li>Ensure that cabling and wiring are secure and avoid hanging clothes on panels or structures.</li>
      <li>Prevent children from being unsupervised in the solar installation area.</li>
    </ul>
  </section>

  <section className="space-y-4">
    <h2 className="text-2xl font-semibold">Rooftop Solar Solutions</h2>

    <div>
      <h3 className="text-xl font-semibold mt-4">Residential Rooftop Solar</h3>
      <p>
        Residential rooftop solar systems offer homeowners an effective way to cut electricity expenses while promoting sustainability. By capturing the sun&apos;s energy, these systems deliver an eco-friendly power source with minimal maintenance requirements.
      </p>
      <ul className="list-disc list-inside space-y-2 mt-2">
        <li>Notable reduction in electricity bills</li>
        <li>Eco-friendly energy source</li>
        <li>Low maintenance requirements</li>
        <li>Increased energy independence</li>
        <li>Opportunity to sell excess power (net metering)</li>
        <li>Available tax incentives and rebates</li>
      </ul>
    </div>

    <div>
      <h3 className="text-xl font-semibold mt-4">Solar Rooftop in Housing Societies</h3>
      <p>
        Implementing solar rooftop systems in housing societies offers collective advantages for all residents, leading to reduced overall energy costs and enhanced sustainability. By utilizing solar power, housing societies can lower their collective carbon footprint and boost the community&apos;s value and appeal.
      </p>
      <ul className="list-disc list-inside space-y-2 mt-2">
        <li>Collective benefits for all residents</li>
        <li>Lower overall energy expenses</li>
        <li>Enhanced sustainability and reduced carbon footprint</li>
        <li>Increased community value and appeal</li>
        <li>Potential for shared energy independence</li>
        <li>Access to government incentives and subsidies</li>
        <li>Decreased pressure on local power grids</li>
      </ul>
    </div>

    <div className="pb-10">
      <h3 className="text-xl font-semibold mt-4">Solar Rooftop for Commercial & Industrial</h3>
      <p>
        Commercial and industrial enterprises can reap significant benefits from installing solar rooftop systems, including substantial reductions in energy costs. These systems enhance energy security and reliability, ensuring consistent operations.
      </p>
      <ul className="list-disc list-inside space-y-2 mt-2">
        <li>Significant reduction in operational energy costs</li>
        <li>Enhanced energy security and reliability</li>
        <li>Strengthened corporate sustainability image</li>
        <li>Compliance with environmental regulations</li>
        <li>Rapid return on investment and long-term savings</li>
        <li>Flexible, scalable solutions for growing energy needs</li>
        <li>Potential for tax benefits and accelerated depreciation</li>
      </ul>
    </div>
  </section>
</div>

    </>
  );
};

export default RooftopSolar;
